apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: gitops-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: redis
        image: redis:alpine
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
