apiVersion: v1
kind: Service
metadata:
  name: java-spring-service
  namespace: gitops-sample
spec:
  selector:
    app: java-spring
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
