apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: gitops-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: redis:alpine
        name: redis
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
