apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: gitops-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: node:alpine
        command: ["node", "app.js"]
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
