apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
  namespace: gitops-sample
spec:
  selector:
    app: python-flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
