apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-deployment
  namespace: gitops-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask
        image: python:alpine
        command: ["python", "app.py"]
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
